### ISSUE TITLE
import ... properties and django >= 1.8

### ISSUE THREAD

**Issue by 94d90b08-c4ef-416c-bf7b-b6c5b7275e6a** [d9pouces/Moneta#3]
Step-by-step installation fails on command `moneta-manage config` on file lib/python3.4/site-packages/moneta/repositories/base.py because `import ... patterns` is deprecated for django 1.8 and excluded (syntax changed) in 1.10.
To fix it i roll back to 1.8 and all works fine.

**Comment by d9pouces** [comment]
Future version will work with Django 1.10 :)
